#!/bin/bash

nbr=0
nombre=0
somme=0
while ((nbr!=1))
do
echo "Saisir une note :"
read note
if [ $note == q ]
then
	echo "Fin Fonction - q sortie"
	nbr=1
elif [ $note -lt 0 ]
then
	echo "Fin Fonctoni - negative sortie"
	nbr=1
elif [ $note -ge 16 -a $note -le 20 ]
then
	echo "Très bien"
elif [ $note -ge 14 -a $note -lt 16 ]
then
	echo "Bien"
elif [ $note -ge 12 -a $note -lt 14 ]
then
	echo "Assez bien"
elif [ $note -ge 10 -a $note -lt 12 ]
then
	echo "Moyen"
elif [ $note -ge 0 -a $note -lt 10 ]
then
	echo "Insuffisant"
else
	echo "note erronée"
fi
nombre=$nombre + 1
somme= $somme + $note
done
moyenne=$somme/$nombre
echo "Moyenne :"
echo $moyenne
