#!/bin/bash

nbr=0
nombre=0
somme=0
while ((nbr!=1))
do
echo "Saisir une note :"
read -r note
if [ "$note" = "q" ];
then
	echo "Fin Fonction - q sortie"
	nbr=1
elif [ "$note" -ge 0 -a "$note" -le 20 ];
then
	if [ "$note" -lt 0 ];
	then
		echo "Fin Fonction - negative sortie"
		nbr=1
	elif [ "$note" -ge 16 -a "$note" -le 20 ];
	then
		echo "Très bien"
	elif [ "$note" -ge 14 ];
	then
		echo "Bien"
	elif [ "$note" -ge 12 ];
	then
		echo "Assez bien"
	elif [ "$note" -ge 10 ];
	then
		echo "Moyen"
	elif [ "$note" -ge 0 ];
	then
		echo "Insuffisant"
	fi
	let nombre=$nombre+1
	let somme=$somme+$note
else
	echo "Note erronée"
fi
done
if [ $nombre -ge 1 ];
then
	let moyenne=$somme/$nombre
	echo "Moyenne : $moyenne ; pour $nombre notes"
fi
echo "Saisir une valeur"
read -r value
result=1
for ((i=0;i<$value;i++));do
	let result=$result*$value
done
echo "$value^$value=$result"
